/*
 *
 *Copyright (C) 刘晓龙
 *Copyright (C) 昆明黑海科技有限公司
 *
 *
 */

/*
 *smart coap 编码
 *
 *
 *作者:Crow
 *时间:2017-05-13
 *最后修改时间:2017-05-13
 */

#ifndef _SMART_COAP_CODE_H_INCLUDE
#define _SMART_COAP_CODE_H_INCLUDE

/*
 *
 */
enum smart_coap_code_msg_type
{
	SMART_COAP_CODE_MSG_TYPE_CON = 0,
	SMART_COAP_CODE_MSG_TYPE_NON,
	SMART_COAP_CODE_MSG_TYPE_ACK,
	SMART_COAP_CODE_MSG_TYPE_RST
};

/*
 *request 相关编码
 */
enum smart_coap_code_req
{
	SMART_COAP_CODE_REQ_GET = 0x01,
	SMART_COAP_CODE_REQ_POST,
	SMART_COAP_CODE_REQ_PUT,
	SMART_COAP_CODE_REQ_DELETE
};

/*
 *respons 相关编码
 */
enum smart_coap_code_res
{
	SMART_COAP_CODE_RES_CREATED = 0x41,
	SMART_COAP_CODE_RES_DELETED,
	SMART_COAP_CODE_RES_VALID,
	SMART_COAP_CODE_RES_CHANGED,
	SMART_COAP_CODE_RES_CONTENT,

	SMART_COAP_CODE_RES_BAD_REQUEST = 0x80,
	SMART_COAP_CODE_RES_UNAUTHORIZED,
	SMART_COAP_CODE_RES_BAD_OPTION,
	SMART_COAP_CODE_RES_FORBIDDEN,
	SMART_COAP_CODE_RES_NOT_FOUND,
	SMART_COAP_CODE_RES_METHOD_NOT_ALLOWED,
	SMART_COAP_CODE_RES_NOT_ACCEPTABLE,
	SMART_COAP_CODE_RES_PRECONDITION_FAILED = 0x8c,
	SMART_COAP_CODE_RES_UNSUPPOR_CONTEN_TYPE = 0X8F,

	SMART_COAP_CODE_RES_INTERNAL_SERVER_ERROR = 0xa0,
	SMART_COAP_CODE_RES_NOT_IMPLEMENTED,
	SMART_COAP_CODE_RES_BAD_GATEWAY,
	SMART_COAP_CODE_RES_SERVICE_UNAVAILABLE,
	SMART_COAP_CODE_RES_GATEWAY_TIMEOUT,
	SMART_COAP_CODE_RES_PROXYING_NOT_SUPPORTED
};

/*
 *option 相关编码
 */
enum smart_coap_code_opt
{
	SMART_COAP_CODE_OPT_IF_MATCH = 1,
	SMART_COAP_CODE_OPT_URI_HOST = 3,
	SMART_COAP_CODE_OPT_ETAG,
	SMART_COAP_CODE_OPT_IF_NONE_MATCH,
	SMART_COAP_CODE_OPT_URI_PORT = 7,
	SMART_COAP_CODE_OPT_LOCATION_PATH,
	SMART_COAP_CODE_OPT_URI_PATH = 11,
	SMART_COAP_CODE_OPT_CONTENT_FORMAT,
	SMART_COAP_CODE_OPT_MAX_AGE = 14,
	SMART_COAP_CODE_OPT_URI_QUERY,
	SMART_COAP_CODE_OPT_ACCEPT = 17,
	SMART_COAP_CODE_OPT_LOCATION_QUERY = 20,
	SMART_COAP_CODE_OPT_PROXY_URI = 35,
	SMART_COAP_CODE_OPT_PROXY_SCHEME = 39,
	SMART_COAP_CODE_OPT_SIZEL = 60
};

/*
 *context format 相关编码
 */
enum smart_coap_code_context_format
{
	SMART_COAP_CODE_CONTEXT_FORMAT_TXT = 0,
	SMART_COAP_CODE_CONTEXT_FORMAT_APP_LINK = 40,
	SMART_COAP_CODE_CONTEXT_FORMAT_APP_XML,
	SMART_COAP_CODE_CONTEXT_FORMAT_APP_OS,
	SMART_COAP_CODE_CONTEXT_FORMAT_APP_EXI = 47,
	SMART_COAP_CODE_CONTEXT_FORMAT_APP_JSON = 50
};

#endif
